version: "3"
services:
  fe:
    volumes:
      - ./fe:/app
    command: npm run serve
  be:
    volumes:
      - ./be:/app
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm run dev"
  cypress:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    environment:
      - DISPLAY
    command: npx cypress open
