version: "3"
services:
  fe:
    environment:
      - "VUE_APP_API_URL=http://be:80"
      - "PORT=80"
  be:
    environment:
      - "NODE_ENV=test"
      - "PORT=80"
  cypress:
    build: ./e2e
    volumes:
      - ./e2e/tests:/e2e/tests
    depends_on:
      - fe
      - be
      - db
    environment:
      - "PORT=8080"
      - "CYPRESS_baseUrl=http://fe:80"
      - "CYPRESS_API_URL=http://be:80"
