version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - checkout
      - store_test_results
      - run:
          name: Run unit and e2e tests
          command: scripts/ci
      - store_artifacts:
          path: e2e/tests/cucumber-json/test.cucumber.json
  deploy_backend:
    machine:
      enabled: true
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
  deploy_frontend:
    machine:
      enabled: true
    steps:
      - checkout
      - deploy:
          name: Front-end build
          command: |
            scripts/build_and_deploy_fe

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy_backend:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy_frontend:
          requires:
            - test
          filters:
            branches:
              only: master
