#!/bin/bash

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  # Linux
  xhost +local:
  DISPLAY=unix${DISPLAY}
else
  # Mac
  IP=$(ipconfig getifaddr en0)
  /usr/X11/bin/xhost + $IP
  DISPLAY=$IP:0
fi

sudo docker-compose -p test -f docker-compose.yml -f docker-compose.test.yml up -d
