#!/bin/bash

if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  # Linux
  xhost +local:
  DISPLAY=unix${DISPLAY}
else
  # Mac
  open -a XQuartz
  IP=$(ipconfig getifaddr en0)
  /usr/X11/bin/xhost + $IP
  DISPLAY=$IP:0
fi

docker-compose -p test -f docker-compose.yml -f docker-compose.test.yml -f docker-compose.e2e.yml up --exit-code-from cypress
